### ISSUE TITLE
Update has-symbols to 1.0.2 to fix "global is not defined" when qs is used

### ISSUE THREAD

**Issue by tonivj5** [ljharb/get-intrinsic#10]
![image](https://user-images.githubusercontent.com/7110786/111767361-ebfb5d80-88a6-11eb-9a8a-33767434ac55.png)

https://github.com/inspect-js/has-symbols/blob/main/CHANGELOG.md#v102---2021-02-27

**Comment by ljharb** [comment]
No update is needed, since `^` is used. You can update it yourself in your lockfile, or, `npm install qs` and it will install the newest version of its transitive dependencies.

The better fix is to fix your broken bundler (webpack 5, presumably) so it properly polyfills node globals.
