### ISSUE TITLE
ERROR - "arguments.callee" cannot be used in strict mode

### ISSUE THREAD

**Issue by ektadesai22** [ljharb/get-intrinsic#11]
ERROR - "arguments.callee" cannot be used in strict mode is coming from node_modules/get-intrinsic/index.js:37

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee
![image](https://user-images.githubusercontent.com/40557245/123135288-3d236c00-d417-11eb-8c6b-6d6192e48be5.png)

The 5th edition of ECMAScript (ES5) forbids use of arguments.callee() in strict mode.

Can you please solve this?

**Comment by ljharb** [comment]
Where are you getting this error? The only use of `callee` is [here](https://github.com/ljharb/get-intrinsic/blob/main/index.js#L28-L43) which is inside a try/catch, so it should be impossible for this error to appear.

**Comment by ljharb** [comment]
Closing pending reproduction information.
