### ISSUE TITLE
What problem is this package solving for?

### ISSUE THREAD

**Issue by derekstavis** [ljharb/get-intrinsic#15]
Hi @ljharb,

While debugging an error coming from the `qs` package -- `intrinsic %close% does not exist!` I stumbled upon this package.

While I want to understand that error, I'm also curious about the problem this package is trying to solve, so would you mind helping me understand why `get-intrinsic` is useful and what problem it is solving?

Appreciate your time!

**Comment by ljharb** [comment]
I'm pretty sure `qs` doesn't try to get an intrinsic called "close", so i'd love to hear more about that :-)

The purpose of this package is stated in the readme; to robustly cache JS language intrinsics (like builtin methods) so that code messing with the builtins doesn't cause packages to break.

**Comment by derekstavis** [comment]
Thanks for the quick response! So just to clarify, when you say "cache JS language intrinsics" you mean preserving the original JS intrinsics so that if a package mutates, e.g.: the Array constructor, it won't break packages requiring intrinsics from `get-intrinsic`?

**Comment by ljharb** [comment]
Yes, exactly right.

**Comment by derekstavis** [comment]
Appreciate the patience, TIL 😄 

About the error -- I can't see how my code could be requesting a `%close%` intrinsic. Here's the Sentry stack trace:

<img width="641" alt="image" src="https://user-images.githubusercontent.com/1611639/163009385-a2d6665e-dcbf-441b-ae69-dc22de9644c6.png">
