### ISSUE TITLE
No matching version found for get-intrinsic@^1.2.2.

### ISSUE THREAD

**Issue by poperechnyi1** [ljharb/get-intrinsic#19]
Hello guys.
I get next error now:
<img width="566" alt="Screenshot 2023-10-21 at 13 25 29" src="https://github.com/ljharb/get-intrinsic/assets/9465302/0618d723-2473-4742-b805-63e9cb2eafa9">

I have checked latest version via command: npm view get-intrinsic

<img width="773" alt="Screenshot 2023-10-21 at 13 28 09" src="https://github.com/ljharb/get-intrinsic/assets/9465302/c652bc94-26f1-452b-9cff-52601b92eda2">

Please fix this issue or suggest what I should do.

**Comment by ljharb** [comment]
It exists: https://unpkg.com/browse/get-intrinsic@1.2.2/

so either it needs some time to filter out to the leaf nodes of various CDNs, or, your private registry isn’t up to date.
