### ISSUE TITLE
GetIntrinsic.js uses unsafe eval

### ISSUE THREAD

**Issue by s3curitybug** [ljharb/get-intrinsic#3]
https://github.com/ljharb/es-abstract/blob/v1.18.0-next.1/GetIntrinsic.js#L21

This line uses Function(), which gets blocked when used with Content Security Policy unless unsafe-eval is used.

**Comment by ljharb** [comment]
The next version of `es-abstract` will use this functionality which has bene extracted into a `get-intrinsic` package, so I've transferred that issue there, since that's where it'll need to be solved.

**Comment by s3curitybug** [comment]
I see the problem. It's about the "async" keyword right? Even if you only execute it inside an if that checks that it is supported, the browser won't even parse the script, right?

I'm afraid there isn't a "clean" way to detect CSP. Basically you can either cause a CSP violation in a try-catch (which already would cause a violation), or do an ajax request to / and check the response headers (which is not clean because it implies doing a request, and it won't detect CSP meta tag configurations, only response header ones).

Any other idea?

**Comment by ljharb** [comment]
It's about the `async` keyword, and also the `*` for generators. Yes, exactly - syntax can't be conditionally parsed without eval.

The only thing I can think of is that apps that use CSP, and know their supported syntax level, can manually alias out individual packages with their bundler.

**Comment by ivanjonas** [comment]
I am pinning my dependencies at older versions that use the older, non-unsafe-eval version of `es-abstract`. I do not have the option of turning off this CSP directive.

**Comment by ljharb** [comment]
@ivanjonas that won’t allow you to use a lot of bugfixes, or any new polyfills/shims, so i don’t think that’s a sustainable approach.

**Comment by s3curitybug** [comment]
@ljharb would you consider creating a new version non-compatible with old browsers? maybe not right now, but in the future...

**Comment by tstehr** [comment]
I just came across this problem when introducing CSP to our webapp. 

The main problem for me is that the `new Function()` call happens at module import time. No code in our app actually to calls `GetIntrinsic` with an argument related to async functions/generators (`AsyncIteratorPrototype`, `AsyncFunction`, `AsyncGenerator`, `AsyncGeneratorFunction`).

Would it be possible to delay it, so that it only happens when on of these intrinsics is actually requested?

For people coming across the issue, for now I've solved it by patching out the problematic part using [string-replace-loader](https://www.npmjs.com/package/string-replace-loader) during our webpack build.

```javascript
{
    test: /\.(js|mjs|jsx|ts|tsx)$/,
        use: {
        loader: 'string-replace-loader',
            options: {
            search: `return Function('"use strict"; return (' + expressionSyntax + ').constructor;')();`,
                replace: 'return undefined;',
        }
    }
}
```

**Comment by ljharb** [comment]
@s3curitybug that would defeat the purpose of the entire es-shims ecosystem, which is to be compatible with every possible JavaScript engine.

@tstehr this is true - the reason it does this is to try to cache the constructor as soon as possible. However, given that these are reachable from syntax and thus impossible to prevent, there’s no reason to eagerly cache them. It would, indeed, be reasonable to defer caching these alone until they’re requested. I’ll look into making that change. Would your CSP settings complain as long as the eval code is never exercised?

**Comment by ljharb** [comment]
The next release should hopefully address this, by deferring `Function` eval until the particular intrinsics are requested.

**Comment by ivanjonas** [comment]
This resolved my issue. Thank you, @ljharb. Here's to hoping none of my dependencies decide to request those particular intrinsics 🤞
