### ISSUE TITLE
Repo contains bad tags

### ISSUE THREAD

**Issue by guimard** [ljharb/get-intrinsic#7]
Hi,

this repository contains tags 1.17.x and 1.18.x that are related to es-abstract, not get-intrinsic. This generates some bugs when updating source to build distribution packages.

Cheers,
Xavier

**Comment by ljharb** [comment]
I prefer my packages only ever be distributed from places where I've distributed them - in general, npm packages shouldn't be installed anywhere but from npm, and only a package author has the context to properly distribute a package.

That said, I'll clean up the tags, thanks.
