### ISSUE TITLE
need export package.json

### ISSUE THREAD

**Issue by axmad386** [ljharb/get-intrinsic#9]
when I use this on svelte, i get this warning.

[rollup-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.

- get-intrinsic

I think is can be fixed as simple as this
https://github.com/niieani/hashids.js/pull/330

**Comment by ljharb** [comment]
Indeed, you're right. Thanks, will be fixed shortly.

**Comment by ljharb** [comment]
v1.1.1 is published.

**Comment by axmad386** [comment]
thanks a lot. I will update it on my project 👍
